### ISSUE TITLE
Documentation for users to add things themselves

### ISSUE THREAD

**Issue by ss23** [adrexia/silverstripe-batch-actions-plus#2]
At the moment, the only documentation is by looking at the code. It would be good to have something in markdown as a quick reference.

**Comment by adrexia** [comment]
Hey, I didn't invent this stuff. It's standard SilverStripe. ;)

Though saying that, SilverStripe probably needs docs. I had to figure it out for myself. The stuff that doesn't require javascript is really easy. The stuff that does is a little more complicated.

**Comment by adrexia** [comment]
And it turns out extending LeftAndMain puts things in the cms menu (duh)... which I hadn't noticed. Fixed now, but need to retest in a normal environment.

**Comment by adrexia** [comment]
Found in docs/en/howto.md
